### PR TITLE
Helm Charts Improvements and Tests

### PR DESCRIPTION
**Pull request by emmanuelmathot**
**Proposed Changes:**

This PR improves the charts management in CI. It adds a workflow for the Helm charts testing:

* Check Version: ensures `current_version` in setup.cfg and `appVersion` in Chart.yaml are the same
* Lint Helm chart
* Test chart deployment on a kind cluster with docker build and check deployment health

**PR Checklist:**

- [X] This PR has **no** breaking changes.
- [X] I have added my changes to the [CHANGELOG](https://github.com/developmentseed/titiler/blob/master/CHANGES.md)

### CODE REVIEW

**Comment by vincentsarago** [comment]
🙏 thanks @emmanuelmathot 

I think I introduced a breaking change in rio-cogeo 🤦 let me see if I can fix this before we merge

**Review by vincentsarago — APPROVED** [review]

**Comment by vincentsarago** [comment]
@emmanuelmathot as usual Helm is not my forte. I approved the PR so you can merge whenever you want ;-)

**Comment by emmanuelmathot** [comment]
Thank you @vincentsarago. I still want to check that the new workflow do not interfere with a new release. I still perform some test in my fork. I let you know.

**Comment by emmanuelmathot** [comment]
To make sure it tests properly before a release, a temporary image is built to be test in the kind cluster.

**Comment by emmanuelmathot** [comment]
> @emmanuelmathot as usual Helm is not my forte. I approved the PR so you can merge whenever you want ;-)

I do not have the rights to merge actually.

**Comment by vincentsarago** [comment]
@emmanuelmathot is it ready to be merged?

**Comment by emmanuelmathot** [comment]
yes it is. Thx

**Pull request merged**
