### PR TITLE
Update intro.md

### PR DESCRIPTION
**Pull request by RichardScottOZ**
Minor corrections

### CODE REVIEW

**Comment by vincentsarago** [comment]
🙏 thanks @RichardScottOZ, really appreciated

**Comment by RichardScottOZ** [comment]
> 🙏 thanks @RichardScottOZ, really appreciated

No worries, note that the customisation link at the bottom of Intro.md gives a 404

**Comment by vincentsarago** [comment]
thanks,

>No worries, note that the customisation link at the bottom of Intro.md gives a 404

Yeah not sure what's going on with those. I had to fix a lot of links on rio-tiler too. I'll take care of this one.

If you have more docs edits, I would suggest to open only one PR (put in WIP, so I don't merge it) and when it's ready just ping me!

**Comment by RichardScottOZ** [comment]
> thanks,
> 
> > No worries, note that the customisation link at the bottom of Intro.md gives a 404
> 
> Yeah not sure what's going on with those. I had to fix a lot of links on rio-tiler too. I'll take care of this one.
> 
> If you have more docs edits, I would suggest to open only one PR (put in WIP, so I don't merge it) and when it's ready just ping me!

Ok, will do, just browsing on tablet while lounging around so just saw this, did a couple more... will use the latest one

**Comment by kylebarron** [comment]
> No worries, note that the customisation link at the bottom of Intro.md gives a 404

The link on the deployed website works for me?

**Comment by vincentsarago** [comment]
@kylebarron I fixed it earlier https://github.com/developmentseed/titiler/commit/f09520221166cc52a7c3ada5fe48142a2ec99a94

**Pull request merged**
