### PR TITLE
[k8s] Define labels in _helpers.tpl

### PR DESCRIPTION
**Pull request by drnextgis**
to avoid code duplication

cc @geospatial-jeff @emmanuelmathot

### CODE REVIEW

**Comment by drnextgis** [comment]
Changes are trivial and I believe that it would be safe to merge. Please review.

**Comment by vincentsarago** [comment]
> Changes are trivial and I believe that it would be safe to merge. Please review.

Hi @drnextgis, I'm sure your intention are good but please be aware this is an open source project, we can't really expect people to jump on PR or issue. We all are our agenda so please be kind. 

If this PR is blocking something for you, please reach out to Devseed and we can setup a contract to give you support.

**Comment by AndreaGiardini** [comment]
+1 LGTM

I've tested it locally and the `helm template` output is consistent.
Nice refactoring @drnextgis

**Comment by emmanuelmathot** [comment]
LGTM branch tested on dev and labels are good.

**Pull request merged**
